const SPOTIFY_ACCESS_TOKEN_EXPIRES_AT_COOKIE_NAME = 'spotify_access_token_expires_at'
const SPOTIFY_REFRESH_TOKEN_COOKIE_NAME = 'spotify_refresh_token'
const SPOTIFY_ACCESS_TOKEN_COOKIE_NAME = 'spotify_access_token'
const SPOTIFY_USER_ID_COOKIE_NAME = 'spotify_user_id'

export {
  SPOTIFY_ACCESS_TOKEN_EXPIRES_AT_COOKIE_NAME,
  SPOTIFY_REFRESH_TOKEN_COOKIE_NAME,
  SPOTIFY_ACCESS_TOKEN_COOKIE_NAME,
  SPOTIFY_USER_ID_COOKIE_NAME,
}
